Update model.py
Change K.control_flow_ops.while_loop to tf.while_loop

Since it gives error AttributeError: module 'keras.backend' has no attribute 'control_flow_ops'